### ISSUE TITLE
There may be unauthorized issues with the Academy badge used by the organization

### ISSUE THREAD

**Issue by ghost** [BUPTSE/welcome#15]
Unofficial organizations (@BUPT) that have previously used the BUPT school badge have been forced to notify that they cannot use it.

https://github.com/bupt

https://bupt.github.io/announcement/bupt-10-1-problem/

So I'm concerned that there might be an infringement of the academy badge if you use it for Github organization :)

**Comment by PersicaMoe** [comment]
Explicit statements have been made on https://github.com/BUPTSE homepage to clarify that the organization is non-official.

Since the School of Software Engineering has ceased to exist, there is currently no plan to remove relevant emblems.

Further discussion about this will be made if we receive notifications from the school officials.
